name: flutter_package_1
description: "Mini SDK per a ReqRes i RestCountries"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.26.0

flutter:
  # Secció requerida encara que no declaris assets, per a packages Flutter.
